{% set name = "azure-nspkg" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-nspkg-{{ version }}.zip
  sha256: e7d3cea6af63e667d87ba1ca4f8cd7cb4dfca678e4c55fc1cedb320760e39dd0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools
  run:
    - python >=3.4

test:
  imports:
    - azure_nspkg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Namespace Package -- Internal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Maxyme
    - xylar
