{% set name = "azure-nspkg" %}
{% set version = "3.0.1" %}
{% set sha256 = "a908f96a695b12e31b6c56cda0bb8e6d2a054283c350881667f300b8563ece33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip  
  run:
    - python
    - setuptools

test:
  imports:
    - azure

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Namespace Package [Internal]'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
